sudo: false

language: node_js
node_js:
    - "6"
    - "8"
    - "10"

os:
  - linux
  - osx

env:
  global:
    ELM_VERSION=0.19.0

install:
  - node --version
  - npm --version
  - npm install

script:
  - npm test
