sudo: false

cache:
  directories:
    - sysconfcpus

language: node_js
node_js:
    - "6"
    - "8"
    - "10"

os:
  - linux
  - osx

env:
  global:
    - ELM_VERSION=0.19.0
    - PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
  matrix:
    - TEST_TARGET=ci.js
    - TEST_TARGET=finder.js
    - TEST_TARGET=flags.js
    - TEST_TARGET=test_versions.js

install:
  - node --version
  - npm --version
  - npm install
  - npm install why-is-node-running

script:
  - mocha tests/$TEST_TARGET
